# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5d1c9a40a4b29117223d09fd162d789f"
name = "section-store"
handle = "section-store-5"
application_url = "https://velvet-automatic-foot-protocol.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "techoweb.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://velvet-automatic-foot-protocol.trycloudflare.com/auth/callback",
  "https://velvet-automatic-foot-protocol.trycloudflare.com/auth/shopify/callback",
  "https://velvet-automatic-foot-protocol.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
